export const GROUP_LIST_REQUEST = "GROUP_LIST_REQUEST"
export const GROUP_LIST_SUCCESS = "GROUP_LIST_SUCCESS"
export const GROUP_LIST_ERROR = "GROUP_LIST_ERROR"

export const ADD_GROUP_ENABLED = "ADD_GROUP_ENABLED"
export const ADD_GROUP_REQUEST = "ADD_GROUP_REQUEST"
export const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS"
export const ADD_GROUP_ERROR = "ADD_GROUP_ERROR"

export const SET_ACTIVE_GROUP = "SET_ACTIVE_GROUP"

export const GET_GROUP_MESSAGES_REQUEST = "GET_GROUP_MESSAGES_REQUEST"
export const GET_GROUP_MESSAGES_SUCCESS = "GET_GROUP_MESSAGES_SUCCESS"
export const GET_GROUP_MESSAGES_ERROR = "GET_GROUP_MESSAGES_ERROR"

export const SEND_GROUP_MESSAGES_REQUEST = "SEND_GROUP_MESSAGES_REQUEST"
export const SEND_GROUP_MESSAGES_SUCCESS = "SEND_GROUP_MESSAGES_SUCCESS"
export const SEND_GROUP_MESSAGES_ERROR = "SEND_GROUP_MESSAGES_ERROR"
